package com.healthcare.modules.modle;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DATAENTITY".
 */
public class dataentity {

    private Long timeStamp;
    private Float x;
    private Float y;
    private Float z;
    private Integer type;
    private Integer accuracy;
    private String tag;

    public dataentity() {
    }

    public dataentity(Long timeStamp, Float x, Float y, Float z, Integer type, Integer accuracy, String tag) {
        this.timeStamp = timeStamp;
        this.x = x;
        this.y = y;
        this.z = z;
        this.type = type;
        this.accuracy = accuracy;
        this.tag = tag;
    }

    public Long getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Long timeStamp) {
        this.timeStamp = timeStamp;
    }

    public Float getX() {
        return x;
    }

    public void setX(Float x) {
        this.x = x;
    }

    public Float getY() {
        return y;
    }

    public void setY(Float y) {
        this.y = y;
    }

    public Float getZ() {
        return z;
    }

    public void setZ(Float z) {
        this.z = z;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getAccuracy() {
        return accuracy;
    }

    public void setAccuracy(Integer accuracy) {
        this.accuracy = accuracy;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public String getCvsFormat(){
        StringBuffer sb = new StringBuffer();
        sb.append(String.valueOf(timeStamp));
        sb.append(" ,");
        sb.append(String.valueOf(x));
        sb.append(" ,");
        sb.append(String.valueOf(y));
        sb.append(" ,");
        sb.append(String.valueOf(z));
        sb.append(" ,");
        sb.append(String.valueOf(accuracy));
        sb.append(" ,");
        sb.append(String.valueOf(type));
        sb.append(" ,");
        sb.append(String.valueOf(tag));
        sb.append("\n");
        return  sb.toString();
    }

}
