package com.healthcare.modules.modle;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "KINETICS".
 */
public class kinetics {

    private Long id;
    private Float anglex;
    private Float angley;
    private Float agnlez;
    private Float accelx;
    private Float accely;
    private Float accelz;
    private Float gyrox;
    private Float gyroy;
    private Float gyroz;

    public kinetics() {
    }

    public kinetics(Long id) {
        this.id = id;
    }

    public kinetics(Long id, Float anglex, Float angley, Float agnlez, Float accelx, Float accely, Float accelz, Float gyrox, Float gyroy, Float gyroz) {
        this.id = id;
        this.anglex = anglex;
        this.angley = angley;
        this.agnlez = agnlez;
        this.accelx = accelx;
        this.accely = accely;
        this.accelz = accelz;
        this.gyrox = gyrox;
        this.gyroy = gyroy;
        this.gyroz = gyroz;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Float getAnglex() {
        return anglex;
    }

    public void setAnglex(Float anglex) {
        this.anglex = anglex;
    }

    public Float getAngley() {
        return angley;
    }

    public void setAngley(Float angley) {
        this.angley = angley;
    }

    public Float getAgnlez() {
        return agnlez;
    }

    public void setAgnlez(Float agnlez) {
        this.agnlez = agnlez;
    }

    public Float getAccelx() {
        return accelx;
    }

    public void setAccelx(Float accelx) {
        this.accelx = accelx;
    }

    public Float getAccely() {
        return accely;
    }

    public void setAccely(Float accely) {
        this.accely = accely;
    }

    public Float getAccelz() {
        return accelz;
    }

    public void setAccelz(Float accelz) {
        this.accelz = accelz;
    }

    public Float getGyrox() {
        return gyrox;
    }

    public void setGyrox(Float gyrox) {
        this.gyrox = gyrox;
    }

    public Float getGyroy() {
        return gyroy;
    }

    public void setGyroy(Float gyroy) {
        this.gyroy = gyroy;
    }

    public Float getGyroz() {
        return gyroz;
    }

    public void setGyroz(Float gyroz) {
        this.gyroz = gyroz;
    }

}
