package com.healthcare.modules.modle;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

import java.util.Date;

/**
 * Entity mapped to table "LOCUS".
 */
public class locus implements Parcelable {

    private Long id;
    private Double longtitude;
    private Double lattitude;
    private Float accuracy;
    private java.util.Date date;
    private String userName;

    public locus() {
    }

    public locus(Long id) {
        this.id = id;
    }

    public locus(Long id, Double longtitude, Double lattitude, Float accuracy, java.util.Date date, String userName) {
        this.id = id;
        this.longtitude = longtitude;
        this.lattitude = lattitude;
        this.accuracy = accuracy;
        this.date = date;
        this.userName = userName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getLongtitude() {
        return longtitude;
    }

    public void setLongtitude(Double longtitude) {
        this.longtitude = longtitude;
    }

    public Double getLattitude() {
        return lattitude;
    }

    public void setLattitude(Double lattitude) {
        this.lattitude = lattitude;
    }

    public Float getAccuracy() {
        return accuracy;
    }

    public void setAccuracy(Float accuracy) {
        this.accuracy = accuracy;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }


    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeValue(this.longtitude);
        dest.writeValue(this.lattitude);
        dest.writeValue(this.accuracy);
        dest.writeLong(date != null ? date.getTime() : -1);
        dest.writeString(this.userName);
    }

    protected locus(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.longtitude = (Double) in.readValue(Double.class.getClassLoader());
        this.lattitude = (Double) in.readValue(Double.class.getClassLoader());
        this.accuracy = (Float) in.readValue(Float.class.getClassLoader());
        long tmpDate = in.readLong();
        this.date = tmpDate == -1 ? null : new Date(tmpDate);
        this.userName = in.readString();
    }

    public static final Parcelable.Creator<locus> CREATOR = new Parcelable.Creator<locus>() {
        public locus createFromParcel(Parcel source) {
            return new locus(source);
        }

        public locus[] newArray(int size) {
            return new locus[size];
        }
    };
}
